import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 * The {@code HomePage} class represents the main welcome screen of the
 * ResolveIt application. It allows users to navigate to their respective
 * login pages: Admin, Student, or Manager.
 */
public class HomePage extends JFrame implements ActionListener {

    /** Button for navigating to Admin login page. */
    JButton adminLoginButton;

    /** Button for navigating to Student login page. */
    JButton studentLoginButton;

    /** Button for navigating to Manager login page. */
    JButton managerLoginButton;

    /**
     * Constructs the main homepage GUI window for the ResolveIt system.
     * Sets up the title, buttons, layout, and heading label.
     */
    public HomePage() {
        setTitle("ResolveIt - Main Menu");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Center the window on screen

        // Heading label
        JLabel heading = new JLabel("Welcome to ResolveIt", SwingConstants.CENTER);
        heading.setFont(new Font("Arial", Font.BOLD, 16));

        // Initialize buttons
        adminLoginButton = new JButton("Admin Login");
        studentLoginButton = new JButton("Student Login");
        managerLoginButton = new JButton("Manager Login");

        // Register action listeners
        adminLoginButton.addActionListener(this);
        studentLoginButton.addActionListener(this);
        managerLoginButton.addActionListener(this);

        // Set layout and add components
        setLayout(new GridLayout(4, 1, 10, 10));
        add(heading);
        add(adminLoginButton);
        add(studentLoginButton);
        add(managerLoginButton);
    }

    /**
     * Handles button click events and opens the corresponding login window.
     * 
     * @param e The ActionEvent generated by a button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == adminLoginButton) {
            new AdminLoginPage().setVisible(true);
            dispose(); // Close current window
        } else if (e.getSource() == studentLoginButton) {
            new StudentLoginPage().setVisible(true);
            dispose();
        } else if (e.getSource() == managerLoginButton) {
            new ManagerLoginPage().setVisible(true);
            dispose();
        }
    }
}
